const piadasRuins = [
    "Por que o livro foi ao médico? Porque ele estava cheio de páginas amarelas.",
    "Qual é o cúmulo da velocidade? Colocar gelo num copo e ele derreter antes de tocar no fundo.",
    "O que o zero disse para o oito? Belo cinto!",
    "Por que a plantinha não sente frio? Porque ela tem folhas.",
    "Como o elétron atende o telefone? Próton!",
    "Por que o lápis acabou com a borracha? Porque ela vivia apagando ele.",
    "Qual é o animal que não vale nada? O javali.",
    "Por que o escorregador foi para a terapia? Porque ele vive deslizando nos problemas.",
    "O que a impressora disse para o papel? ‘Esse é o menor dos seus problemas… vou te imprimir!’",
    "Por que o calendário é sempre humilde? Porque os dias estão contados.",
    "Por que o fotógrafo foi preso? Porque ele foi revelado.",
    "Qual é o peixe mais inteligente? O ‘A-mém’… porque nada de errado.",
    "Por que o pote de manteiga não perde a linha? Porque ele é margarina.",
    "Por que o estudante levou uma escada pra escola? Para subir de série.",
    "O que o Wi-Fi disse para o celular? ‘A conexão entre nós é forte.’",
    "Por que o jacaré tirou o filho da escola? Porque ele reptilhou.",
    "Como o pão se comunica? Pelo mio-te.",
    "Por que o suco de laranja não gosta de correr? Porque ele se concentra.",
    "Qual é o café que vive reclamando? O descafeinado.",
    "Por que a vaca não usa fone? Porque ela já tem orelhas de vaca.",
    "O que o pato disse para a pata? Vem Quá!",
    "Por que o menino colocou o despertador embaixo da cama? Para acordar em cima da hora.",
    "Qual é o rei dos queijos? O Reiqueijão.",
    "O que uma impressora falou para a outra? Essa folha é sua ou é impressão minha?",
    "Qual é o contrário de volátil? Vem cá tio.",
    "Por que o bombeiro não gosta de andar? Porque ele socorre.",
    "Qual é o doce preferido do átomo? Pé-de-molécula.",
    "O que o tomate foi fazer no banco? Foi tirar extrato.",
    "Qual a cidade que não tem táxi? Uberlândia.",
    "Por que a velhinha não usa relógio? Porque ela é sem hora.",
    "O que o Java disse para o C? Você não tem classe!",
    "Qual é a peça de carro que é feita no Egito? O faraol.",
    "Por que o rádio não pode ter filhos? Porque ele é estéreo.",
    "O que acontece se chover na Inglaterra? Vira Inglalama.",
    "Qual é a panela que está sempre triste? A panela de depressão.",
    "O que o pagodeiro foi fazer na igreja? Cantar Pá-god.",
    "Por que o computador foi ao médico? Porque estava com vírus.",
    "Qual é o vinho que não tem álcool? O Ovinho de codorna.",
    "Para que serve o óculos verde? Para verde perto.",
    "O que a Lua disse ao Sol? Nossa, você é tão grande e não te deixam sair à noite!",
    "Como se chama a tristeza de um carneiro? Lã-mentável.",
    "Por que o policial não usa sabão em pó? Porque ele prefere deter-gente.",
    "Qual o estado que queria ser um veículo? Sergipe (Ser Jeep).",
    "O que o canibal vegetariano come? A planta do pé e a batata da perna.",
    "Por que as estrelas não fazem miau? Porque Astronomia.",
    "Qual é o cúmulo da paciência? Esperar sentado em uma cadeira elétrica.",
    "Por que o relógio foi ao psicólogo? Porque estava passando por uma fase difícil.",
    "Qual é o peixe que caiu do céu? O atum.",
    "Por que o lápis não gosta de viajar? Porque ele sempre volta apontado.",
    "Qual é o animal mais antigo? A zebra, porque está em preto e branco.",
    "Por que o celular foi para a escola? Para ganhar mais crédito.",
    "Qual é o cúmulo da distração? Esquecer a própria piada ruim.",
    "Por que o sapato não conta segredo? Porque ele é fechado.",
    "Qual é o cúmulo da força? Dobrar a esquina.",
    "Por que o cachorro entrou na igreja? Porque ele é pastor alemão.",
    "Qual é o cúmulo da fome? Comer o prato de comida.",
    "Por que o peixe não gosta de internet? Porque tem medo da rede.",
    "Qual é o cúmulo da preguiça? Deitar na cama e pedir carona pro sono.",
    "Por que o lápis é humilde? Porque ele sempre se apaga.",
    "Qual é o cúmulo da organização? Guardar segredo em pasta suspensa.",
    "Por que o queijo olhou para trás? Porque o réqueijão.",
    "Qual é o doce que vive rindo? A paçoca (pá-soca!).",
    "O que o café disse para o pão de queijo? 'Juntos, somos mineiramente perfeitos.'",
    "Por que a cenoura nunca se perde? Porque ela tem olhos (haha).",
    "Qual é o sanduíche favorito do ET? O de 'humanos' com mostarda.",
    "O que a formiga disse para a formiga-gigante? 'Oi, tia!'",
    "Por que o tubarão não come palhaço? Porque ele tem medo de palhaçada.",
    "Qual é o animal que mais usa criptografia? O canguru, porque ele tem uma bolsa forte.",
    "Por que a aranha é o bicho mais carente da internet? Porque ela vive em web.",
    "O que o gato disse quando perdeu todos os seus 9 rabos? 'Estou des-rabado.'",
    "Por que o celular foi para a geladeira? Para baixar os aplicativos.",
    "O que o USB disse para a porta USB? 'Podemos nos conectar mais tarde?'",
    "Por que o algoritmo foi para a terapia? Porque tinha muitos problemas de lógica mal resolvidos.",
    "Como o robô serve o café? Com 'inteligência artificial' (e muito derramado).",
    "Por que o fone de ouvido brigou com o celular? Porque ele não se sentia 'escutado'.",
    "O que a porta disse para a chave? 'Me dá uma volta, vamos sair.'",
    "O que o lápis de cor disse para a canetinha? 'Você é muito marcante na minha vida.'",
    "O que a nuvem disse para a outra nuvem? 'Vamos chover ou vamos apenas flutuar?'",
    "O que o passado disse para o futuro? 'Você é muito previsível.'",
    "O que o copo vazio disse para o copo cheio? 'Você está muito cheio de si.'",
    "Qual é o cúmulo do azar? Cair da cama e quebrar o chão.",
    "Por que a bicicleta não consegue ficar em pé sozinha? Porque ela é de dois tempos.",
    "Qual é o cúmulo da altura? Cair do quinto andar e reclamar da queda livre.",
    "Por que a matemática é o assunto mais romântico? Porque tem muitos 'corações' (raiz quadrada).",
    "O que é um pontinho preto no avião? Uma 'aviãozinho'.",
    "Se um vegetal sonha, ele vira um 'sonho de verão'?",
    "Por que o espelho nunca mente? Porque ele sempre reflete a verdade (e seus cabelos bagunçados).",
    "O que o silêncio disse para o barulho? 'Nada.'",
    "Se o tempo é relativo, por que minha reunião sempre dura uma eternidade?",
    "Por que a piada ruim foi para a academia? Para ficar 'em forma' (de groans).",
    "Por que o pintor nunca se perde? Porque ele sempre segue as linhas.",
    "Qual é o cúmulo da arquitetura? Construir um prédio de histórias (mas sem elevador).",
    "Por que o astronauta não janta? Porque ele já está cheio de estrelas.",
    "O que o relógio da padaria disse para o padeiro? 'É hora de fazer as horas.'",
    "Por que o carteiro é o funcionário mais otimista? Porque ele sempre acredita que vai dar 'entrega'.",
    "Qual é o nome do animal que vive na mão? O anel.",
    "O que o garfo disse para a faca? 'Você tem um tempero especial, mas eu sou mais prato.'",
    "Por que o museu pegou fogo? Porque estava cheio de *artes*.",
    "O que a banana disse para o macaco? 'Eu te amo, mas não sou sua casca!'.",
    "Qual é o cantor favorito do cego? O *Dado* Dolabella.",
    "Por que o pescador não é bom de briga? Porque ele *só vive na isca*.",
    "O que o espermatozoide disse para o outro? 'Vamos nos apressar, o chefe tá na cabeça!'",
    "Por que o pinheiro não se perde na floresta? Porque ele tem uma *pinha* (um PIN).",
    "Qual é o cúmulo da burrice? Levar um camundongo para passear na frente de um PC (Mouse).",
    "O que a formiga quebrou no hospital? Uma *formatura*.",
    "Qual é o dia da semana que o ovo odeia? A *segunda-feira* (gema de segunda).",
    "O que a nuvem de chuva disse para o Sol? 'Você não tem brilho próprio!'",
    "Por que o jacaré usa colete? Para proteger o *réptil-torácico*.",
    "Qual é a piada do fotógrafo? É que ela ainda está *em desenvolvimento*.",
    "O que o fogo disse para a fumaça? 'Eu sou o máximo, você é só um desfumado.'",
    "O que o parafuso disse para a porca? 'Não me *aperte*, meu amor!'",
    "Qual é o animal que não tem inimigos? O *amigato*.",
    "Por que o muro não usa cueca? Porque ele tem *cal*.",
    "O que a água disse para o óleo? 'Não podemos nos misturar, você é *muito solto*.'",
    "Por que a geladeira ficou triste? Porque o freezer não deu *gelo*.",
    "Qual é o cúmulo da miséria? Comer miojo e torcer para o terceiro minuto passar rápido.",
    "O que um SD Card disse para o outro? 'Você está cheio de *memória*.'",
    "Por que o frango atravessou a rua? Para mostrar que não era *galinha*.",
    "O que o leão foi fazer na rua? Foi dar um *passeio real*.",
    "Qual é o cúmulo do otimismo? Um esqueleto esperando vaga para dentista.",
    "O que o zero disse para o nove? 'Para de se exibir, eu também sou um número *redondo*.'",
    "Por que o mar não briga com o rio? Porque ele tem *onda*.",
    "Qual é o cúmulo da injustiça? Um band-aid no joelho de um robô.",
    "O que o alface disse para o pão? 'Vamos fazer uma *salada* de ideias.'",
    "Por que o pato é o melhor DJ? Porque ele faz *quá-quá* (cut-cut).",
    "Qual é o animal que vive debaixo da terra e adora cinema? O *toupeira-pipoca*.",
    "O que é um pontinho amarelo no meio da floresta? Um *milho no mato*.",
    "O que o sabonete disse para o shampoo? 'Estamos na mesma *espuma*.'",
    "Por que o pneu de carro não estuda? Porque ele *roda* demais.",
    "Qual é o cúmulo do raciocínio? Pensar de trás para frente.",
    "O que o pintinho disse para a mãe? 'Mãe, estou chocado!'",
    "Por que a internet é tão barulhenta? Porque ela tem muitos *megabytes*.",
    "Qual é o peixe que nasceu em Marte? O *Peixe-Extraterrestre* (sem trocadilho, só ruim).",
    "O que o vento disse para a palmeira? 'Segura a *onda*, vou te levar para um luau!'",
    "Por que o espantalho ganhou um prêmio? Porque ele foi *excelente em seu campo*.",
    "Por que o semáforo nunca mente? Porque ele sempre dá sinal.",
    "O que o teclado disse para o computador? 'Não me pressione!'",
    "Por que a girafa não usa óculos? Porque ela já enxerga lá de cima.",
    "O que o gelo disse para a água? 'Tô só dando um tempo.'",
    "Por que o fantasma não mente? Porque você pode ver através dele.",
    "O que o chinelo disse para o pé? 'Pisa em mim não, pô!'",
    "Por que o matemático não briga com ninguém? Porque ele sempre resolve na raiz.",
    "O que o motor disse para a gasolina? 'Sem você eu não funciono.'",
    "Por que o astronauta levou uma colher pro espaço? Para pegar um pouco de céu.",
    "O que o garçom falou quando o livro caiu no chão? 'Caiu a ficha!'",
        "Por que o código binário foi ao psicólogo? Porque só tinha 0 problemas.",
    "O que o café disse para o leite? 'Juntos somos um expresso!'",
    "Por que o hamster foi ao banco? Para abrir uma conta-corrente de sementes.",
    "Qual é o cúmulo do azar no Minecraft? Cair em lava com diamante e o backup corromper.",
    "O que a uva passinha falou para a uva normal? 'Eu só passei para dizer oi.'",
    "Por que o pombo não usa computador? Porque ele prefere o pigeon (pigeon = pombo em inglês).",
    "O que o lápis 6B disse para o 2H? 'Você é muito duro comigo.'",
    "Por que o jacaré do TikTok ficou famoso? Porque ele sempre postava stories.",
    "Qual é o cúmulo da economia? Usar o verso do papel higiênico já usado.",
    "O que o NFT disse para a obra de arte? 'Agora você vale milhões, mas só digitalmente.'",
    "Por que a cenoura foi presa? Porque ela estava no raiz (no rolê).",
    "O que o guarda-chuva falou para a chuva? 'Você me deixa aberto a novas possibilidades.'",
    "Por que o Minecraft é o jogo mais sociável? Porque todo mundo se encontra no multiplayer.",
    "Qual é o prato preferido do Superman? Kryptonita com batata (mentira, ele não come kryptonita).",
    "O que a pilha falou para a outra? 'Estou ficando sem energia para essa relação.'",
    "Por que o pombo-correio foi demitido? Porque só entregava nas árvores.",
    "O que o algoritmo de recomendação disse? 'Você talvez goste dessa piada... ou não.'",
    "Por que o celular antigo não brinca no escorregador? Porque ele tem medo de cair (e quebrar).",
    "Qual é o animal que mais sabe de tecnologia? O cachorro, porque ele tem Windows (janelas) e mouse.",
    "O que o tecido falou para a tesoura? 'Corta essa relação!'",
    "Por que a lâmpada foi ao médico? Porque estava com medo de queimar a largada.",
    "Qual é o cúmulo da sorte? Encontrar um atum no meio do deserto.",
    "O que o caderno disse para a caneta? 'Você sempre me marca.'",
    "Por que a formiga não entra no metrô? Porque ela não tem bilhete único.",
    "O que o controle remoto falou para a TV? 'Não mude de canal nossa relação.'",
    "Por que o cachorro do programador late em binário? '101101 WOOF!'",
    "Qual é o doce que vive atrasado? O marshmallow (marcha-melhor).",
    "O que a nuvem de dados disse? 'Estou cheia de informações, mas vazia de sentimentos.'",
    "Por que o elefante não joga videogame? Porque ele tem medo do mouse.",
    "Qual é o cúmulo da ironia? Uma porta giratória em uma casa de um andar.",
    "O que o post-it disse para a parede? 'Vou grudar em você para sempre.'",
    "Por que o sapo não usa Facebook? Porque ele já tem o Twitter (ribbit).",
    "O que o jacaré disse para o jornal? 'Você está cheio de notícias répteis.'",
    "Qual é o animal que mais gosta de cinema? O cachorro, porque ele vê filme de 'Os Pinguins do Papai'.",
    "O que o GPS falou para o carro? 'Siga em frente, mas não esqueça de voltar.'",
    "Por que a água mineral é tão educada? Porque ela sempre dá lugar para o gás.",
    "Qual é o cúmulo da preguiça digital? Deixar o celular carregando em 1% e assistir até acabar.",
    "O que o Minecraft disse para o jogador? 'Você me constrói e me destrói.'",
    "Por que o frango do Minecraft cruzou a estrada? Para chegar ao outro chunk.",
    "O que o algoritmo de shuffle disse? 'Essa playlist é aleatória, mas sempre toca as mesmas músicas.'",
    "Qual é o animal que mais sabe de leis? O jabuti, porque ele sempre recorre.",
    "O que o código CSS disse para o HTML? 'Você dá estrutura, mas eu dou estilo.'",
    "Por que o cachorro do designer não late? Porque ele é um 'cachorro vetorial'.",
    "Qual é o cúmulo da modernidade? Pedir um delivery de água da torneira.",
    "O que o hub USB disse? 'Todos vocês podem se conectar a mim, mas um de cada vez.'",
    "Por que o pombo não é bom em matemática? Porque ele só sabe contar até pombos.",
    "O que a bateria de 99% disse para a de 100%? 'Você está cheia de si.'",
    "Qual é o animal que mais gosta de animes? O gato, porque ele vê 'Neko no Ongaeshi'.",
    "O que o teclado mecânico disse? 'CLICK CLACK CLACK CLACK' (essa nem precisa de punchline).",
    "Por que o jogo indie nunca briga? Porque ele é muito independente.",
    "O que o pixel disse para o outro? 'Juntos formamos algo maior.'",
    "Qual é o cúmulo da tecnologia? Um smartwatch que avisa quando você está perdendo tempo.",
    "O que o meme falou para a internet? 'Você me criou, mas não me controla.'",
    "Por que a água do mar não é confiável? Porque ela sempre está mudando de onda.",
    "Qual é o animal que mais sabe de moda? A aranha, porque ela sempre está tecendo.",
    "O que o hambúrguer vegano disse? 'Sou igual, mas diferente.'",
    "Por que o código foi ao terapeuta? Porque tinha muitos loops infinitos.",
    "O que a lua disse para a terra? 'Você gira em torno de mim... espera, é o contrário.'",
    "Qual é o cúmulo da sorte no jogo? Encontrar um glitch que te dá infinitas vidas.",
    "O que o DNS disse para o site? 'Eu te encontro em qualquer lugar.'",
    "Por que o caderno de caligrafia é triste? Porque ele vive nas linhas.",
    "O que o sol disse para a sombra? 'Você sempre me persegue.'",
    "Qual é o animal que mais gosta de música clássica? A baleia, porque ela canta em dó maior.",
    "O que o fone Bluetooth disse para o celular? 'Nosso relacionamento é sem fio, mas forte.'",
    "Por que o livro de matemática é dramático? Porque ele tem muitos problemas.",
    "O que o vírus de computador disse? 'Não sou mal, só quero me espalhar.'",
    "Qual é o cúmulo da ecologia? Reciclar o papel da prova que você errou.",
    "O que o grão de areia disse para o outro? 'Juntos formamos uma praia de ideias.'",
    "Por que o interruptor não tem amigos? Porque ele só liga e desliga.",
    "O que o algoritmo de busca falou? 'Encontrei 1.000.000 de resultados, mas nenhuma resposta.'",
    "Qual é o animal que mais gosta de festa? O polvo, porque ele dança com oito braços.",
    "O que a nuvem de chuva disse para o guarda-chuva? 'Você sempre me bloqueia.'",
    "Por que o roteador é o rei da casa? Porque todos se curvam a ele para pegar Wi-Fi.",
    "Qual é o cúmulo da realidade virtual? Chorar com um filme usando o headset.",
    "O que o cookie disse para o navegador? 'Me guarde para sempre.'",
    "Por que o cachorro do youtuber late em 4K? Porque ele é um influencer canino.",
    "O que o teclado disse para o mouse? 'Você me aponta, mas eu escrevo a história.'",
    "Qual é o animal que mais sabe de geografia? O tatu, porque ele sempre está em uma bola.",
    "O que o planeta Saturno disse? 'Meus anéis são melhores que os do casamento.'",
    "Por que o jogo de tabuleiro não briga? Porque ele sempre segue as regras.",
    "O que o post do Instagram disse? 'Ganhei likes, mas perdi a essência.'",
    "Qual é o cúmulo da automação? Um robô que faz piadas ruins sobre humanos.",
    "O que a bateria de lítio disse? 'Sou leve, mas potente.'",
    "Por que o pombo não é bom em relacionamentos? Porque ele sempre dá ghosting.",
    "O que o código aberto falou? 'Sou livre, mas preciso de manutenção.'",
    "Qual é o animal que mais gosta de café? O javali, porque ele vive no mato (e o café é do mato).",
    "O que a lâmpada inteligente disse? 'Posso mudar de cor, mas não de opinião.'",
    "Por que o banco de dados foi à festa? Porque ele sabia todas as queries (curiosidades).",
    "Qual é o cúmulo da internet? Um meme que explica a vida mas ninguém entende.",
    "O que o satélite disse para a Terra? 'Sempre de olho em você.'",
    "Por que o celular não fica bravo? Porque ele sempre está no modo avião.",
    "O que a plantinha do apartamento disse? 'Minha vida é um vaso de desafios.'",
    "Qual é o animal que mais sabe de história? A tartaruga, porque ela viveu tudo.",
    "O que o fogo do Minecraft disse? 'Sou útil, mas perigoso.'",
    "Por que o algoritmo de compras sempre erra? Porque ele acha que você precisa de outra piada ruim."
];

module.exports = piadasRuins;